import Head from "next/head";
import HeroSection from "../components/hero_section/HeroSection";

export default function Home() {
  return (
    // bg-[#E5E5E5]
    <div className="">
      <Head>
        <title>WindTravels</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <main>
        <HeroSection />
      </main>
    </div>
  );
}
